  name: CI - Projeto Bilhete

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Instalar GCC
      run: sudo apt-get update && sudo apt-get install -y gcc

    - name: Compilar arquivos
      run: gcc -o test.out bilhete.c main.c test.c

    - name: Executar testes
      run: ./test.out
